### ISSUE TITLE
ImportError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed?

### ISSUE THREAD

**Issue by stealdre** [openslide/openslide-python#146]
I'm trying to use openslide on an Apple Silicon Mac (ARM).

**What I did:**

```
brew install openslide
python3 -m venv env 
source env/bin/activate
pip install openslide-python 
```

**What I get:**

```
Traceback (most recent call last):
  File "/Users/paulbeneteau/Documents/GitHub/PyHisto-Electron/backend/./deepzoom_server.py", line 30, in <module>
    import openslide
  File "/Users/paulbeneteau/Documents/GitHub/PyHisto-Electron/backend/env/lib/python3.9/site-packages/openslide/__init__.py", line 35, in <module>
    from openslide import lowlevel
  File "/Users/paulbeneteau/Documents/GitHub/PyHisto-Electron/backend/env/lib/python3.9/site-packages/openslide/lowlevel.py", line 56, in <module>
    raise ImportError("Couldn't locate OpenSlide dylib.  " +
ImportError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed?
```

**Comment by bgilbert** [comment]
Probably Brew doesn't install OpenSlide in the dylib search path.  Mixing package managers can be a bit dicey for that reason.

**Comment by stealdre** [comment]
Should I create a link to dylib ?

**Comment by stealdre** [comment]
Here is what I did to make it works:

`sudo ln -s /opt/homebrew/lib/libopenslide.dylib //usr/local/lib/libopenslide.dylib`
