### ISSUE TITLE
I have successfully done all the preliminary work, but failed when running the example py code

### ISSUE THREAD

**Issue by brisker** [openslide/openslide-python#16]
I have successfully build the packages, but when I try to run deepzoom_tile.py ,I got the following error:
sudo python deepzoom_tile.py
[sudo] password for wangdu: 
Traceback (most recent call last):
  File "deepzoom_tile.py", line 26, in <module>
    import openslide
  File "/usr/local/lib/python2.7/dist-packages/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "/usr/local/lib/python2.7/dist-packages/openslide/lowlevel.py", line 55, in <module>
    _lib = cdll.LoadLibrary('libopenslide.so.0')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

How can I solve this problem?

**Comment by GlastonburyC** [comment]
Running into the same issue? Any luck?

**Comment by bgilbert** [comment]
That error means that OpenSlide Python can't find your OpenSlide library.

**Comment by j-sieger** [comment]
@bgilbert :  
Yes, you are correct. but i could not find library file in any path. If i could find the files then atleast i can figure out some solution.
