### ISSUE TITLE
Missing _convert.cpython-310-darwin.so

### ISSUE THREAD

**Issue by barrettMCW** [openslide/openslide-python#225]
### Operating system

MacOS13 Ventura

### Platform

ARM64

### OpenSlide Python version

1.3.0

### OpenSlide version

3.4.1

### Slide format

NA

### Issue details

Issues installing openslide-python on ventura. the cython appears to not be compiling correctly, always gets compiled for x86
Current workaround goes as follows:
Install openslide-python==1.2.0
copy lib/python3.10/site-packages/openslide/_convert.cpython-310-darwin.so to temp location
upgrade to openslide-python==1.3.0
copy old .so file to new package.
Let me know if I can do anything to help, Thanks!

**Comment by bgilbert** [comment]
Could you post the command you're using to install OpenSlide Python, and the resulting output?

**Comment by barrettMCW** [comment]
sure thing! here's the output:
```bash
mjbarrett@RAD-170744 ~ % arch -arm64 /opt/homebrew/bin/python3 -m pip cache purge
WARNING: No matching packages
Files removed: 0
mjbarrett@RAD-170744 ~ % arch -arm64 /opt/homebrew/bin/python3 -m venv test
mjbarrett@RAD-170744 ~ % arch -arm64 test/bin/python3 -m pip install openslide-python
Collecting openslide-python
  Downloading openslide-python-1.3.0.tar.gz (358 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.9/358.9 kB 8.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow (from openslide-python)
  Obtaining dependency information for Pillow from https://files.pythonhosted.org/packages/e4/93/9226cc667ed8785333969c03deb2a36af2f3757284d3a2cf2ebd70331c32/Pillow-10.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Downloading Pillow-10.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.5 kB)
Downloading Pillow-10.0.1-cp311-cp311-macosx_11_0_arm64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 19.4 MB/s eta 0:00:00
Building wheels for collected packages: openslide-python
  Building wheel for openslide-python (pyproject.toml) ... done
  Created wheel for openslide-python: filename=openslide_python-1.3.0-cp311-cp311-macosx_13_0_arm64.whl size=26033 sha256=23f680804f13c0319f0853a3454d0b7e4363903528f65f448c9a7185bfca0cfd
  Stored in directory: /Users/mjbarrett/Library/Caches/pip/wheels/75/f2/b4/8a416a8f3c107db18b12d6255bcc00e4d6aa589d538395207c
Successfully built openslide-python
Installing collected packages: Pillow, openslide-python
Successfully installed Pillow-10.0.1 openslide-python-1.3.0
mjbarrett@RAD-170744 ~ % arch -arm64 test/bin/python3                                
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import openslide
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mjbarrett/test/lib/python3.11/site-packages/openslide/__init__.py", line 31, in <module>
    from openslide import lowlevel
  File "/Users/mjbarrett/test/lib/python3.11/site-packages/openslide/lowlevel.py", line 51, in <module>
    from . import _convert
ImportError: dlopen(/Users/mjbarrett/test/lib/python3.11/site-packages/openslide/_convert.cpython-311-darwin.so, 0x0002): tried: '/Users/mjbarrett/test/lib/python3.11/site-packages/openslide/_convert.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/mjbarrett/test/lib/python3.11/site-packages/openslide/_convert.cpython-311-darwin.so' (no such file), '/Users/mjbarrett/test/lib/python3.11/site-packages/openslide/_convert.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by bgilbert** [comment]
Hmm, it works for me:

```console
m1@test ~ % arch -arm64 /opt/homebrew/bin/python3 -m pip cache purge
Files removed: 12
m1@test ~ % arch -arm64 /opt/homebrew/bin/python3 -m venv test
m1@test ~ % arch -arm64 test/bin/python3 -m pip install openslide-python
Collecting openslide-python
  Downloading openslide-python-1.3.0.tar.gz (358 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.9/358.9 kB 27.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow (from openslide-python)
  Obtaining dependency information for Pillow from https://files.pythonhosted.org/packages/e4/93/9226cc667ed8785333969c03deb2a36af2f3757284d3a2cf2ebd70331c32/Pillow-10.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Downloading Pillow-10.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.5 kB)
Downloading Pillow-10.0.1-cp311-cp311-macosx_11_0_arm64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 91.0 MB/s eta 0:00:00
Building wheels for collected packages: openslide-python
  Building wheel for openslide-python (pyproject.toml) ... done
  Created wheel for openslide-python: filename=openslide_python-1.3.0-cp311-cp311-macosx_13_0_arm64.whl size=26432 sha256=1ae4a5ca77228df79ed26907b3360fc698a8aaa292f384c22ade17ee990d65a3
  Stored in directory: /Users/m1/Library/Caches/pip/wheels/75/f2/b4/8a416a8f3c107db18b12d6255bcc00e4d6aa589d538395207c
Successfully built openslide-python
Installing collected packages: Pillow, openslide-python
Successfully installed Pillow-10.0.1 openslide-python-1.3.0
m1@test ~ % arch -arm64 test/bin/python3
Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import openslide
>>> 
```

Is it possible that your local setup is misconfigured in some way?  OpenSlide Python doesn't do anything unusual to build the C extension module, so this seems unlikely to be an OpenSlide Python issue.

**Comment by bgilbert** [comment]
I'll close for now.  If you have any additional info pointing to an OpenSlide Python problem, please feel free to post it here.
