### ISSUE TITLE
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gangli95** [openslide/openslide-python#39]
## Context

**Issue type**
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory
**Operating system**: 
Centos6 (without administrator rights)
**Platform**
x64  
**OpenSlide Python version** 
python3.5  openslide-python 1.1.1

## Details
I tried to install from source and using pip ,but both occured this issue.  I also exported the path when I installed from source(`export LD_LIBRARY_PATH=~/openslide-python-1.1.1:$LD_LIBRARY_PATH` ) , but it didn't work.  If there is any solution for this issues, please tell me. Thanks!
here is the output of error:
`Python 3.5.0 |Continuum Analytics, Inc.| (default, Oct 19 2015, 21:57:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openslide
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/DATA/249/gli1/software/openslide-python-1.1.1/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File "/DATA/249/gli1/software/openslide-python-1.1.1/openslide/lowlevel.py", line 58, in <module>
    _lib = cdll.LoadLibrary('libopenslide.so.0')
  File "/DATA/249/gli1/software/Anaconda3/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/DATA/249/gli1/software/Anaconda3/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory
`

**Comment by j-sieger** [comment]
@gangli95 @bgilbert 

Can you please provide the solution for this. I am facing the same issue on Amazon linux server
