### ISSUE TITLE
Inconsistent output read_region() local vs server

### ISSUE THREAD

**Issue by Nurfen** [openslide/openslide-python#66]
Hello,

I've noted an inconsistency when extracting patches from a .tiff image.
The attached images are the output of the same openslide.read_region() command,
One ran locally on a Mac computer and the other on a linux server. 

It looks like the 'y-0' reference point doesn't start at the actual 0,0 point, as the image is shifted down a little bit. Moreover the image extracted on the server is less detailed than the original image.

other strange phenomena are different level dimensions for the same slide
server side:
((164352, 84480), (82432, 42496), (41472, 21504), (20480, 10752), (10240, 5632), (5120, 3072), (2560, 1536), (1536, 1024), (1024, 512), (512, 512))

local:
((164352, 84480), (82176, 42240), (41088, 21120), (20544, 10560), (10272, 5280), (5136, 2640), (2568, 1320), (1284, 660), (642, 330), (321, 165))

The attached images are extracted on zoom level = 3 so the difference in dimensions could explain the reduction in image detail on the server side.

Moreover If I try to extract a large region near the bottom of the slide on the server I get the following error:

TIFFFillTile: 0: Invalid tile byte count, tile 53.
Traceback (most recent call last):
  File "src/run_model.py", line 159, in <module>
    OS.extract_from_slide('output/test_rem_z5.png', 25600, 51200,5,(1000,1000))
  File "src/run_model.py", line 129, in extract_from_slide
    tile = self.slide.read_region((x, y), zoom_level, size)
  File "/env/lib/python3.6/site-packages/openslide/__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "/env/lib/python3.6/site-packages/openslide/lowlevel.py", line 259, in read_region
    _read_region(slide, buf, x, y, level, w, h)
  File "/env/lib/python3.6/site-packages/openslide/lowlevel.py", line 196, in _check_error
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: TIFFRGBAImageGet failed

You would expect a corrupted .tiff image, but I copied the image from the server to my pc locally. 
So if the .tiff image would be corrupt, it shouldn't function on my pc locally.

On the server side the openslide package is run in a docker container, which installs all the following packages:
RUN apt-get update && apt-get -y install git libglib2.0-0 libsm6 curl libevent-dev gcc libxext6 libxrender-dev poppler-utils openslide-tools python-openslide python3-dev

Maybe some of these interfere with the openslide package.

Any ideas?

Thanks in advance!

![test_local](https://user-images.githubusercontent.com/16961387/71662305-43b8b200-2d51-11ea-8c5d-25dcdcbed367.png)
![test_rem](https://user-images.githubusercontent.com/16961387/71662310-4915fc80-2d51-11ea-8895-9a22ff4b4f18.png)

**Comment by Nurfen** [comment]
It might be related to the following issue:
https://github.com/openslide/openslide/issues/238 

I'll report back

**Comment by Nurfen** [comment]
Updating to openslide version 3.4.1 did the trick.
I had to add the below to the docker file (taken from [here](https://github.com/Steven-N-Hart/openslide-docker/blob/master/Dockerfile))

```

RUN git clone https://github.com/uclouvain/openjpeg.git
RUN cd openjpeg && mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release && make && make install && make clean

RUN git clone https://github.com/openslide/openslide.git
RUN cd openslide && autoreconf -i && ./configure && make && make install

RUN wget https://github.com/openslide/openslide/releases/download/v3.4.1/openslide-3.4.1.tar.gz
RUN tar xvzf openslide-3.4.1.tar.gz
RUN cd openslide-3.4.1 && ./configure && make && make install && cd / ```
