### ISSUE TITLE
Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each)

### ISSUE THREAD

**Issue by shaokeke** [openslide/openslide-python#88]
Context

Issue type** (bug report): 
Operating system** (Windows 10): 
Platform** (64-bit x86,): 
OpenSlide Python version** (`py3.6.10`): 
OpenSlide version** (`openslide.__library_version__`): 
**Slide format** (SVS,): 

Details:
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
C:\Users\sk\Desktop\python\openslide-python-master\examples\deepzoom\slide\ftv0fno1ontsv4ce2d1cpaj0_0.svs: Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each).
TIFFReadDirectory: Failed to read directory at offset 858581370.
C:\Users\sk\Desktop\python\openslide-python-master\examples\deepzoom\slide\ftv0fno1ontsv4ce2d1cpaj0_0.svs: Failed to allocate memory for to read TIFF directory (0 elements of 12 bytes each).
TIFFReadDirectory: Failed to read directory at offset 858581370.
127.0.0.1 - - [18/Aug/2020 12:28:57] "[37mGET /ftv0fno1ontsv4ce2d1cpaj0_0.svs HTTP/1.1[0m" 200 -
127.0.0.1 - - [18/Aug/2020 12:28:57] "[37mGET /ftv0fno1ontsv4ce2d1cpaj0_0.svs.dzi HTTP/1.1[0m" 200 -
[2020-08-18 12:29:15,583] ERROR in app: Exception on /ftv0fno1ontsv4ce2d1cpaj0_0.svs_files/8/0_0.jpeg [GET]
Traceback (most recent call last):
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "deepzoom_multiserver.py", line 160, in tile
    tile = slide.get_tile(level, (col, row))
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\openslide\deepzoom.py", line 150, in get_tile
    tile = self._osr.read_region(*args)
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\openslide\__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "C:\Users\sk\anaconda3\envs\pviewer\lib\site-packages\openslide\lowlevel.py", line 258, in read_region
    buf = (w * h * c_uint32)()
MemoryError

**Comment by shaokeke** [comment]
aperio open is ok:
![image](https://user-images.githubusercontent.com/37448773/90471766-9a90c180-e151-11ea-87ce-c6f1dfd12e7e.png)
openslide open : TIFFReadDirectory: Failed to read directory at offset 858581370

**Comment by shaokeke** [comment]
and Memory up and up
![image](https://user-images.githubusercontent.com/37448773/90472280-b6489780-e152-11ea-8732-71c83ea03c61.png)

**Comment by shaokeke** [comment]
https://slice-telepathcloud.oss-cn-shanghai.aliyuncs.com/ybl2ossmove/202008/17/92_b5c63040533829f93b6b43f0a71b2486/ftv0fno1ontsv4ce2d1cpaj0_0.svs

**Comment by shaokeke** [comment]
this svs file  levelCount=1
